[package]
name = "egui_custom"
version = "0.3.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18"

[dependencies.job_queue]
path = "../job_queue"
